### ISSUE TITLE
What's this?

### ISSUE THREAD

**Issue by SamuelHiroyuki** [usmanmohammed/mysql-entityframework-prototype#1]
namespace BrainPunch.Models

{

using MySql.Data.Entity;

using System;

using System.Data.Entity;

using System.Linq;

**[DbConfigurationType(typeof(MySqlEFConfiguration))]** 

public class DatabaseContext : DbContext

{

// Your context has been configured to use a 'DatabaseContext' connection string from your application's 

// configuration file (App.config or Web.config). By default, this connection string targets the 

// 'BrainPunch.Models.DatabaseContext' database on your LocalDb instance. 

// 

// If you wish to target a different database and/or database provider, modify the 'DatabaseContext' 

// connection string in the application configuration file.

public DatabaseContext()

: base("DefaultConnection")

{

}

// Add a DbSet for each entity type that you want to include in your model. For more information 

// on configuring and using a Code First model, see http://go.microsoft.com/fwlink/?LinkId=390109.

public virtual DbSet<Member> Members { get; set; }

public virtual DbSet<Game_Schedule> GameSchedules { get; set; }

}

}

-------
I'm refering to the bold code. What he does?

(English is not my primary language)

**Comment by usmanmohammed** [comment]
Hi, sorry for my late reply.

**[DbConfigurationType(typeof(MySqlEFConfiguration))]** is optional but highly recommended, because it adds all the dependency resolvers for MySQL classes. 

There are other ways of achieving the same goal. You can read more about the implementations here: https://dev.mysql.com/doc/connector-net/en/connector-net-entityframework60.html
